# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903f08d25b2b47af9e230675a1b8296b4abc279a9fb4dddcbaafffe70db45a01b161d6b4d79d0ff2fe61b17a054668ce226cb53a140e3e8c78bf2f9e1beb6195

test:
  secret_key_base: 8e29a002e74091f83a2c7b3266bb775f80957912f0a63f3c28bf0bb3339d3a2d2a2c1123a9a923326c4b739edee453c37628c27174718321280e955993dfd785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
